# DB
db.driver=org.mariadb.jdbc.Driver
db.url=jdbc:mysql://203.194.114.182:3306/maintenance_monitoring_v2?autoReconnect=true&useSSL=false
db.username=goldspice
db.password=9L2AewPCUthgua2hQNOOhJ108O10N0d5MrXa7EmJidk=
db.pool-size=1

encryption.salt.length=6

staff.default.password=P@ssw0rd

# Audit configuration
audit.enable=true

# Email server configuration
## Gmail account sample tsi.sup.sample@gmail.com / SecretP@ssw0rd

# Email Microservice
mail.ms.server=http://localhost:9090/mail-service/api
mail.ms.send-email.api=/mail/send
mail.ms.key-name=x-api-key
mail.ms.api-key=akxGNBuGXeSjPzSIrtdisguJMbEgRtrGakbaeWAk

mail.sender=no-reply@tsi.com


# OTP configuration
## OTP expiry in minutes
otp.test.enable=true
otp.test.code=123456
otp.expiry=10
otp.retry.count=3
otp.link.format=http://localhost:8080/otp

password.reset.link.format=http://203.194.114.182:8080/monitoring/login#reminder

